# Generated by Django 5.2.6 on 2025-09-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profiles/profile_login.png', upload_to='profiles/'),
        ),
    ]
