# Generated by Django 5.2.6 on 2025-09-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_phone_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
