# Generated by Django 5.2.6 on 2025-09-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_code_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_code_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
