# Generated by Django 5.2.6 on 2025-09-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guests',
        ),
    ]
