# Generated by Django 5.2.6 on 2025-09-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_reservation_guests'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'time')},
        ),
    ]
